"""Configurations, workloads, and runs.

Creating a run does not execute it. The API records the intent and returns; the
orchestrator picks it up. That split exists because a run takes minutes to hours — an
HTTP request cannot hold it, and more importantly a control-plane restart must not kill
work in flight (ROADMAP 0.4.0).
"""

from __future__ import annotations

import uuid
from typing import Annotated, Any

from fastapi import APIRouter, HTTPException, Query, Response, status
from fastapi.responses import PlainTextResponse
from sqlalchemy import Select, func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import InstrumentedAttribute, aliased, selectinload

from vllmbench_api.config_validation import validate_config
from vllmbench_api.deps import SessionDep
from vllmbench_api.hashing import _slug, config_hash, normalize_yaml, workload_hash
from vllmbench_api.schemas import (
    ConfigAnnotate,
    ConfigCreate,
    ConfigOut,
    ConfigValidationOut,
    ConfigValidationRequest,
    EngineSampleOut,
    FindingOut,
    GpuSampleOut,
    LineageNode,
    LineageOut,
    RunCreate,
    RunOut,
    RunTelemetryOut,
    WorkloadCreate,
    WorkloadOut,
)
from vllmbench_db.enums import RunStatus
from vllmbench_db.models import (
    ConfigJustification,
    EngineSample,
    GpuHost,
    GpuSample,
    Run,
    RunTelemetryPruned,
    ServerConfig,
    Workload,
)
from vllmbench_protocol.serve_args import (
    ServeArguments,
    load_serve_arguments,
    reference_serve_arguments,
)

router = APIRouter(prefix="/api", tags=["runs"])


# ---------------------------------------------------------------------------
# Configurations
# ---------------------------------------------------------------------------


@router.post("/configs", response_model=ConfigOut, status_code=status.HTTP_201_CREATED)
async def create_config(payload: ConfigCreate, session: SessionDep) -> ServerConfig:
    digest = config_hash(payload.yaml)

    # Content addressing means re-submitting the same YAML is idempotent rather than an
    # error. Sweep authoring will do exactly that, repeatedly.
    existing = await session.scalar(select(ServerConfig).where(ServerConfig.config_hash == digest))
    if existing is not None:
        return existing

    # Lineage is recorded only on creation. A config that already exists has a history
    # that already happened, and letting a later submission rewrite its parent would make
    # the derivation chain depend on who submitted last rather than on what was edited.
    parent_id = None
    if payload.parent_id is not None:
        parent = await session.get(ServerConfig, payload.parent_id)
        if parent is None:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"no config with id {payload.parent_id}",
            )
        parent_id = parent.id

    config = ServerConfig(
        config_hash=digest,
        name=payload.name,
        yaml=normalize_yaml(payload.yaml),
        notes=payload.notes,
        parent_id=parent_id,
    )
    session.add(config)
    await session.commit()
    await session.refresh(config)
    return config


async def _config_by_hash(session: AsyncSession, config_hash_value: str) -> ServerConfig:
    config = await session.scalar(
        select(ServerConfig).where(ServerConfig.config_hash == config_hash_value)
    )
    if config is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="config not found")
    return config


@router.get("/configs/{config_hash_value}/export", response_class=PlainTextResponse)
async def export_config(config_hash_value: str, session: SessionDep) -> Response:
    """The configuration as a file, byte for byte.

    This is the 0.7.0 acceptance criterion in one endpoint: the winning configuration from
    a sweep, exported and run in production unchanged. So nothing is added to it — no
    provenance header, no "generated by" comment, no reordering. A comment would not change
    what vLLM does, but it *would* change the hash, and then the file in production is no
    longer the file that was measured. The point of this endpoint is that those are the
    same bytes.

    The provenance lives at the other end of the link: the hash in the filename is the way
    back to the run that justified it.
    """
    config = await _config_by_hash(session, config_hash_value)
    # Named for what it is and which one it is. A directory of `config.yaml` files tells
    # nobody anything, and the short hash is enough to find the row again.
    filename = f"{_slug(config.name)}-{config.config_hash[:12]}.yaml"
    return PlainTextResponse(
        content=config.yaml,
        media_type="application/yaml",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


async def _with_justification(session: AsyncSession, config: ServerConfig) -> ConfigOut:
    """A config plus its justification, flattened onto one response.

    Two tables, one payload. The split exists to keep the schema acyclic, not because a
    caller should have to know about it.
    """
    justification = await session.scalar(
        select(ConfigJustification).where(ConfigJustification.server_config_id == config.id)
    )
    out = ConfigOut.model_validate(config)
    if justification is not None:
        out.justified_by_run_id = justification.run_id
        out.justification_note = justification.note
    return out


@router.patch("/configs/{config_hash_value}", response_model=ConfigOut)
async def annotate_config(
    config_hash_value: str, payload: ConfigAnnotate, session: SessionDep
) -> ConfigOut:
    """Change what is *said about* a configuration, never the configuration.

    The YAML is not editable here and there is no endpoint where it is. Editing the text
    produces different bytes, which is a different content hash, which is a different
    configuration — so an edit is a creation, and `parent_id` is what connects the two. A
    config whose text could change would silently invalidate every run that claims it.
    """
    config = await _config_by_hash(session, config_hash_value)

    if payload.name is not None:
        config.name = payload.name
    if payload.notes is not None:
        config.notes = payload.notes

    existing = await session.scalar(
        select(ConfigJustification).where(ConfigJustification.server_config_id == config.id)
    )

    if payload.clear_justification:
        if existing is not None:
            await session.delete(existing)
    elif payload.justified_by_run_id is not None:
        run = await session.get(Run, payload.justified_by_run_id)
        if run is None:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"no run with id {payload.justified_by_run_id}",
            )
        if run.config_hash != config.config_hash:
            # The whole value of the link is that it points at evidence. A run of some
            # other configuration is not evidence for this one, and a link that can be
            # wrong is worse than no link.
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    "that run did not use this configuration "
                    f"(it ran {run.config_hash[:12]}…), so it cannot justify it"
                ),
            )
        if existing is None:
            session.add(
                ConfigJustification(
                    server_config_id=config.id,
                    run_id=run.id,
                    note=payload.justification_note,
                )
            )
        else:
            existing.run_id = run.id
            if payload.justification_note is not None:
                existing.note = payload.justification_note
    elif payload.justification_note is not None and existing is not None:
        existing.note = payload.justification_note

    await session.commit()
    await session.refresh(config)
    return await _with_justification(session, config)


#: How far back a lineage walk will go before giving up. Deep chains are real — tuning is
#: iterative — but an unbounded walk over a self-referencing column is a query that can
#: hang on data no API path can produce and some future import might.
MAX_LINEAGE_DEPTH = 100


@router.get("/configs/{config_hash_value}/lineage", response_model=LineageOut)
async def config_lineage(config_hash_value: str, session: SessionDep) -> LineageOut:
    """Where this configuration came from, and what came from it.

    One level of children rather than a whole tree: the question a reader has in front of
    a config is "what did I try next", and a full descendant tree of a much-edited
    baseline is a page of noise.
    """
    config = await _config_by_hash(session, config_hash_value)

    ancestors: list[ServerConfig] = []
    seen = {config.id}
    current = config
    truncated = False
    while current.parent_id is not None:
        if len(ancestors) >= MAX_LINEAGE_DEPTH or current.parent_id in seen:
            truncated = True
            break
        parent = await session.get(ServerConfig, current.parent_id)
        if parent is None:
            break
        ancestors.append(parent)
        seen.add(parent.id)
        current = parent

    children = list(
        (
            await session.execute(
                select(ServerConfig)
                .where(ServerConfig.parent_id == config.id)
                .order_by(ServerConfig.created_at.desc())
            )
        ).scalars()
    )

    return LineageOut(
        config_hash=config.config_hash,
        ancestors=[LineageNode.model_validate(a) for a in ancestors],
        children=[LineageNode.model_validate(c) for c in children],
        truncated=truncated,
    )


@router.get("/configs", response_model=list[ConfigOut])
async def list_configs(session: SessionDep) -> list[ConfigOut]:
    """Every configuration, newest first, each with its justification if it has one.

    The justification is joined in here rather than left null, because a list where the
    field is always empty reads as "nothing is justified" rather than "this endpoint does
    not tell you" — and the whole point of recording it is that somebody sees it.
    """
    configs = list(
        (
            await session.execute(select(ServerConfig).order_by(ServerConfig.created_at.desc()))
        ).scalars()
    )

    # Built by hand rather than with dict(rows.all()): a two-column Row resolves to
    # dict's bytes overload, which type-checks and then fails at runtime.
    justifications: dict[uuid.UUID, ConfigJustification] = {}
    for justification in (await session.execute(select(ConfigJustification))).scalars():
        justifications[justification.server_config_id] = justification

    out: list[ConfigOut] = []
    for config in configs:
        item = ConfigOut.model_validate(config)
        if (found := justifications.get(config.id)) is not None:
            item.justified_by_run_id = found.run_id
            item.justification_note = found.note
        out.append(item)
    return out


# ---------------------------------------------------------------------------
# Workloads
# ---------------------------------------------------------------------------

_WORKLOAD_IDENTITY_FIELDS = (
    "dataset_name",
    "dataset_path",
    "hf_name",
    "num_prompts",
    "request_rate",
    "max_concurrency",
    "burstiness",
    "input_len",
    "output_len",
    # Part of the identity, because it is part of what gets sent. Two blazedit workloads
    # differing only in --blazedit-min-distance are different traffic; leaving this out
    # made them hash identically, so the second create returned the first and a sweep
    # across "both" ran one of them twice while reporting a difference between two.
    "extra_args",
)


@router.post("/workloads", response_model=WorkloadOut, status_code=status.HTTP_201_CREATED)
async def create_workload(payload: WorkloadCreate, session: SessionDep) -> Workload:
    # The name is deliberately not part of the identity: two workloads that send the
    # same traffic are the same workload, whatever they are called.
    identity = {field: getattr(payload, field) for field in _WORKLOAD_IDENTITY_FIELDS}
    digest = workload_hash(identity)

    existing = await session.scalar(select(Workload).where(Workload.workload_hash == digest))
    if existing is not None:
        return existing

    workload = Workload(workload_hash=digest, name=payload.name, **identity)
    session.add(workload)
    await session.commit()
    await session.refresh(workload)
    return workload


@router.get("/workloads", response_model=list[WorkloadOut])
async def list_workloads(session: SessionDep) -> list[Workload]:
    result = await session.execute(select(Workload).order_by(Workload.created_at.desc()))
    return list(result.scalars())


# ---------------------------------------------------------------------------
# Runs
# ---------------------------------------------------------------------------


@router.post("/runs", response_model=RunOut, status_code=status.HTTP_202_ACCEPTED)
async def create_run(payload: RunCreate, session: SessionDep) -> Run:
    """Queue a run. 202, not 201: the work has been accepted, not done."""
    host = await session.get(GpuHost, payload.gpu_host_id)
    config = await session.get(ServerConfig, payload.server_config_id)
    workload = await session.get(Workload, payload.workload_id)

    missing = [
        name
        for name, value in (
            ("gpu_host_id", host),
            ("server_config_id", config),
            ("workload_id", workload),
        )
        if value is None
    ]
    if missing:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=f"unknown {', '.join(missing)}"
        )
    assert host is not None and config is not None and workload is not None

    run = Run(
        gpu_host_id=host.id,
        server_config_id=config.id,
        workload_id=workload.id,
        status=RunStatus.QUEUED,
        # Provenance copied at creation, not joined at read time. What is knowable now
        # is recorded now; the rest is filled in by the orchestrator from what actually
        # ran (invariant 6).
        config_hash=config.config_hash,
        workload_hash=workload.workload_hash,
        gpu_count=max(1, host.gpu_count),
        # Invariant 7's chain of custody: the host's declaration, made by the agent
        # itself, decides whether this run is quarantined. Nothing infers it.
        is_synthetic=host.synthetic_source is not None,
        synthetic_source=host.synthetic_source,
        initiated_by=payload.initiated_by,
        initiated_by_client=payload.initiated_by_client,
    )
    session.add(run)
    await session.commit()
    # `summary` is eager-loaded explicitly (it is None for a fresh run) because the
    # relationship is lazy="raise_on_sql". Serializing without this would attempt a lazy
    # load inside the response model and fail — which is precisely what that setting is
    # for: turning a runtime MissingGreenlet into an obvious, immediate error.
    await session.refresh(run, attribute_names=["summary"])
    return run


@router.get("/runs", response_model=list[RunOut])
async def list_runs(session: SessionDep, limit: int = 50) -> list[Run]:
    result = await session.execute(
        select(Run)
        .options(selectinload(Run.summary))
        .order_by(Run.queued_at.desc())
        .limit(min(limit, 200))
    )
    return list(result.scalars())


@router.get("/runs/{run_id}", response_model=RunOut)
async def get_run(run_id: uuid.UUID, session: SessionDep) -> Run:
    run = await session.get(Run, run_id, options=[selectinload(Run.summary)])
    if run is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="run not found")
    return run


def _stride(total: int, budget: int | None) -> int:
    """How many samples to skip so that at most ``budget`` survive.

    1 means "return everything", which is both the unasked-for case and the case where
    the series is already shorter than the budget.
    """
    if budget is None or budget <= 0 or total <= budget:
        return 1
    return -(-total // budget)  # ceiling division


def _thinned(
    model: type[EngineSample] | type[GpuSample],
    run_id: uuid.UUID,
    stride: int,
    partition: InstrumentedAttribute[int] | None,
) -> Select[Any]:
    """Select a series, keeping every ``stride``-th sample **within each partition**.

    The partition is the load-bearing part. `gpu_sample` is keyed per device and stored
    interleaved, so thinning the flat series takes every nth *row*, not every nth
    *reading*: at stride 2 on a two-GPU host that is every sample from device 0 and none
    at all from device 1. The result looks like a healthy single-device series, arrives
    labelled with both devices, and is exactly the imbalance-destroying summary the
    `gpu_sample` keying rule in CLAUDE.md exists to prevent.

    The last sample of each partition is always kept. A run's final reading is the one
    that says what state it ended in, and dropping it because the series length did not
    divide evenly would silently move the end of the chart.
    """
    order = [model.sampled_at, *([partition] if partition is not None else [])]
    if stride == 1:
        return select(model).where(model.run_id == run_id).order_by(*order)

    numbered = (
        select(
            model,
            func.row_number().over(partition_by=partition, order_by=model.sampled_at).label("rn"),
            func.count().over(partition_by=partition).label("total"),
        )
        .where(model.run_id == run_id)
        .subquery()
    )
    entity = aliased(model, numbered)
    keep = or_((numbered.c.rn - 1) % stride == 0, numbered.c.rn == numbered.c.total)
    # Ordered off the subquery's columns rather than the alias's attributes, so this
    # stays one code path for both models instead of needing to know which one it has.
    entity_order = [
        numbered.c.sampled_at,
        *([numbered.c[partition.key]] if partition is not None else []),
    ]
    return select(entity).where(keep).order_by(*entity_order)


@router.get("/runs/{run_id}/telemetry", response_model=RunTelemetryOut)
async def get_run_telemetry(
    run_id: uuid.UUID,
    session: SessionDep,
    max_samples: Annotated[int | None, Query(ge=1)] = None,
) -> RunTelemetryOut:
    """The engine and per-device series for one run.

    A separate endpoint rather than an expansion of the run payload: a long run can carry
    thousands of samples, and the runs list polls every two seconds while anything is in
    flight. Attaching telemetry to that would multiply the cost of the poll by the size
    of the largest run on the page.

    Per device, never aggregated here. One device at 60% while its peer sits at 95% is
    the finding; the mean of the two is not (invariant 8, and the `gpu_sample` keying
    rule in CLAUDE.md).

    `max_samples` thins the response **in the database**, so a caller that wants two
    hundred points out of fourteen thousand does not pay to load fourteen thousand. It
    bounds each series: the engine series, and the GPU series as a whole — the per-device
    budget is the total divided by the device count, so asking for less does not quietly
    cost a device. Unset returns everything, which is what the timeline chart wants.
    """
    if await session.get(Run, run_id) is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="run not found")

    engine_total = (
        await session.scalar(
            select(func.count()).select_from(EngineSample).where(EngineSample.run_id == run_id)
        )
    ) or 0

    # Built by hand rather than with dict(rows.all()): a two-column Row resolves to
    # dict's bytes overload, which type-checks and then fails at runtime.
    per_device: dict[int, int] = {}
    for index, count in (
        await session.execute(
            select(GpuSample.gpu_index, func.count())
            .where(GpuSample.run_id == run_id)
            .group_by(GpuSample.gpu_index)
        )
    ).all():
        per_device[index] = count

    # One stride across every device, taken from the busiest, rather than a stride each.
    # Devices should produce the same number of samples but need not — a failed NVML
    # read on one device is a real thing — and thinning them by different factors would
    # put the two series on different time grids, which is the one thing that makes an
    # imbalance unreadable.
    #
    # The device floor beats the budget: with a budget smaller than the device count,
    # every device still returns a sample. Overshooting a context limit is recoverable;
    # a device that silently is not there is not.
    device_budget = (
        max(1, max_samples // len(per_device)) if max_samples and per_device else max_samples
    )
    engine_stride = _stride(engine_total, max_samples)
    gpu_stride = _stride(max(per_device.values(), default=0), device_budget)

    engine = list(
        (await session.execute(_thinned(EngineSample, run_id, engine_stride, None))).scalars()
    )
    gpu = list(
        (
            await session.execute(_thinned(GpuSample, run_id, gpu_stride, GpuSample.gpu_index))
        ).scalars()
    )

    # An empty series needs its explanation attached, not inferred. "The policy removed
    # this" and "sampling failed" look identical on a chart and mean opposite things.
    pruned = await session.get(RunTelemetryPruned, run_id)

    return RunTelemetryOut(
        run_id=run_id,
        engine=[EngineSampleOut.model_validate(s) for s in engine],
        gpu=[GpuSampleOut.model_validate(s) for s in gpu],
        pruned_at=pruned.pruned_at if pruned else None,
        pruned_horizon_days=pruned.horizon_days if pruned else None,
        # From the counts, not from what came back. These are the devices that sampled,
        # which is a fact about the run rather than about this response.
        gpu_indices=sorted(per_device),
        sample_count=engine_total + sum(per_device.values()),
        stride=max(engine_stride, gpu_stride),
    )


async def resolve_arguments(
    session: AsyncSession, gpu_host_id: uuid.UUID | None
) -> tuple[ServeArguments, bool, int | None]:
    """Pick the argument catalogue to check against, and say how well it fits.

    A host running a version we have no capture for is not an error — the version policy
    in CLAUDE.md makes benchmarking one vLLM against another a first-class use, so this
    falls back to the reference and reports that it did. Silently checking a 0.26 config
    against 0.25's arguments and calling it valid would be the wrong kind of helpful.
    """
    if gpu_host_id is None:
        return reference_serve_arguments(), True, None

    host = await session.get(GpuHost, gpu_host_id)
    if host is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="host not found")

    if host.vllm_version:
        captured = load_serve_arguments(host.vllm_version)
        if captured is not None:
            return captured, True, host.gpu_count
    return reference_serve_arguments(), False, host.gpu_count


@router.post("/configs/validate", response_model=ConfigValidationOut)
async def validate_config_endpoint(
    payload: ConfigValidationRequest, session: SessionDep
) -> ConfigValidationOut:
    """Check a configuration before it costs a model load.

    Reads only. Nothing is stored, nothing is rewritten, and a config that fails here can
    still be created — the engine describes a file, it does not police one. That matters
    because the catalogue is a capture of one vLLM version, and a host running something
    newer may legitimately accept an argument this service has never heard of.
    """
    arguments, exact, gpu_count = await resolve_arguments(session, payload.gpu_host_id)
    result = validate_config(
        payload.yaml,
        arguments,
        gpu_count=gpu_count,
        exact_version_match=exact,
        tensor_parallel_is_swept=payload.tensor_parallel_is_swept,
    )
    return ConfigValidationOut(
        valid=result.valid,
        findings=[
            FindingOut(
                severity=str(f.severity),
                message=f.message,
                key=f.key,
                line=f.line,
                suggestion=f.suggestion,
            )
            for f in result.findings
        ],
        checked_against=result.checked_against,
        exact_version_match=result.exact_version_match,
    )
