"""initial schema

Creates the results store and the triggers that enforce its immutability rules.

The triggers are not belt-and-braces. CLAUDE.md states that a terminal run is never
mutated and that telemetry tables are append-only, and an invariant enforced only by
convention is one that survives exactly until the first piece of code that finds it
inconvenient. Recorded measurements are the thing this project exists to protect, so the
database refuses the write rather than trusting every future caller to remember.

Revision ID: 50a658ccc86e
Revises:
Create Date: 2026-08-16 11:38:15.170172
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "50a658ccc86e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Immutability enforcement
# ---------------------------------------------------------------------------

_RUN_IMMUTABILITY = """
CREATE OR REPLACE FUNCTION vllmbench_reject_terminal_run_update()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IN ('succeeded', 'failed', 'cancelled') THEN
        RAISE EXCEPTION
            'run % is terminal (status=%) and cannot be modified; re-run instead',
            OLD.id, OLD.status
            USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER run_immutable_when_terminal
    BEFORE UPDATE ON run
    FOR EACH ROW
    EXECUTE FUNCTION vllmbench_reject_terminal_run_update();
"""

_APPEND_ONLY = """
CREATE OR REPLACE FUNCTION vllmbench_reject_sample_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        '% is append-only; telemetry samples are never updated in place',
        TG_TABLE_NAME
        USING ERRCODE = 'raise_exception';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER engine_sample_append_only
    BEFORE UPDATE ON engine_sample
    FOR EACH ROW EXECUTE FUNCTION vllmbench_reject_sample_mutation();

CREATE TRIGGER gpu_sample_append_only
    BEFORE UPDATE ON gpu_sample
    FOR EACH ROW EXECUTE FUNCTION vllmbench_reject_sample_mutation();
"""

_DROP = """
DROP TRIGGER IF EXISTS run_immutable_when_terminal ON run;
DROP TRIGGER IF EXISTS engine_sample_append_only ON engine_sample;
DROP TRIGGER IF EXISTS gpu_sample_append_only ON gpu_sample;
DROP FUNCTION IF EXISTS vllmbench_reject_terminal_run_update();
DROP FUNCTION IF EXISTS vllmbench_reject_sample_mutation();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpu_host",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("agent_url", sa.Text(), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("protocol_version", sa.Integer(), nullable=True),
        sa.Column("vllm_version", sa.String(length=64), nullable=True),
        sa.Column("driver_version", sa.String(length=64), nullable=True),
        sa.Column("cuda_version", sa.String(length=32), nullable=True),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_host")),
        sa.UniqueConstraint("name", name=op.f("uq_gpu_host_name")),
    )
    op.create_index(op.f("ix_gpu_host_created_at"), "gpu_host", ["created_at"], unique=False)
    op.create_table(
        "model",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hf_id", sa.String(length=256), nullable=False),
        sa.Column("revision", sa.String(length=128), nullable=False),
        sa.Column("quantization", sa.String(length=32), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model")),
        sa.UniqueConstraint(
            "hf_id", "revision", "quantization", name=op.f("uq_model_hf_id_revision_quantization")
        ),
    )
    op.create_index(op.f("ix_model_created_at"), "model", ["created_at"], unique=False)
    op.create_table(
        "workload",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workload_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("dataset_name", sa.String(length=64), nullable=False),
        sa.Column("dataset_path", sa.Text(), nullable=True),
        sa.Column("hf_name", sa.String(length=256), nullable=True),
        sa.Column("num_prompts", sa.Integer(), nullable=False),
        sa.Column("request_rate", sa.Float(), nullable=True),
        sa.Column("max_concurrency", sa.Integer(), nullable=True),
        sa.Column("burstiness", sa.Float(), nullable=True),
        sa.Column("input_len", sa.Integer(), nullable=True),
        sa.Column("output_len", sa.Integer(), nullable=True),
        sa.Column("extra_args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workload")),
        sa.UniqueConstraint("workload_hash", name=op.f("uq_workload_workload_hash")),
    )
    op.create_index(op.f("ix_workload_created_at"), "workload", ["created_at"], unique=False)
    op.create_table(
        "gpu_device",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("gpu_host_id", sa.Uuid(), nullable=False),
        sa.Column("device_index", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=True),
        sa.Column("vram_bytes", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gpu_host_id"],
            ["gpu_host.id"],
            name=op.f("fk_gpu_device_gpu_host_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_device")),
        sa.UniqueConstraint(
            "gpu_host_id", "device_index", name=op.f("uq_gpu_device_gpu_host_id_device_index")
        ),
    )
    op.create_index(op.f("ix_gpu_device_gpu_host_id"), "gpu_device", ["gpu_host_id"], unique=False)
    op.create_table(
        "server_config",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("yaml", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_id"], ["model.id"], name=op.f("fk_server_config_model_id")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["server_config.id"], name=op.f("fk_server_config_parent_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_server_config")),
        sa.UniqueConstraint("config_hash", name=op.f("uq_server_config_config_hash")),
    )
    op.create_index(
        op.f("ix_server_config_created_at"), "server_config", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_server_config_model_id"), "server_config", ["model_id"], unique=False)
    op.create_index(
        op.f("ix_server_config_parent_id"), "server_config", ["parent_id"], unique=False
    )
    op.create_table(
        "sweep",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="sweep_status",
            ),
            nullable=False,
        ),
        sa.Column("gpu_host_id", sa.Uuid(), nullable=False),
        sa.Column("replicates", sa.Integer(), nullable=False),
        sa.Column("initiated_by", sa.Enum("ui", "api", "mcp", name="initiated_by"), nullable=False),
        sa.Column("initiated_by_client", sa.String(length=128), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gpu_host_id"], ["gpu_host.id"], name=op.f("fk_sweep_gpu_host_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sweep")),
    )
    op.create_index(op.f("ix_sweep_created_at"), "sweep", ["created_at"], unique=False)
    op.create_index(op.f("ix_sweep_gpu_host_id"), "sweep", ["gpu_host_id"], unique=False)
    op.create_index(op.f("ix_sweep_is_synthetic"), "sweep", ["is_synthetic"], unique=False)
    op.create_index(op.f("ix_sweep_status"), "sweep", ["status"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sweep_id", sa.Uuid(), nullable=True),
        sa.Column("replicate_idx", sa.Integer(), nullable=False),
        sa.Column("server_config_id", sa.Uuid(), nullable=False),
        sa.Column("workload_id", sa.Uuid(), nullable=False),
        sa.Column("gpu_host_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "starting",
                "benchmarking",
                "succeeded",
                "failed",
                "cancelled",
                name="run_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("workload_hash", sa.String(length=64), nullable=False),
        sa.Column("vllm_version", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("protocol_version", sa.Integer(), nullable=True),
        sa.Column("driver_version", sa.String(length=64), nullable=True),
        sa.Column("cuda_version", sa.String(length=32), nullable=True),
        sa.Column("gpu_model", sa.String(length=128), nullable=True),
        sa.Column("dataset_identity", sa.Text(), nullable=True),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("device_indices", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("tensor_parallel_size", sa.Integer(), nullable=False),
        sa.Column("pipeline_parallel_size", sa.Integer(), nullable=False),
        sa.Column(
            "bench_client_location",
            sa.Enum("loopback", "remote", name="bench_client_location"),
            nullable=False,
        ),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column(
            "synthetic_source",
            sa.Enum("mock_agent", "fake_vllm", "cpu_backend", name="synthetic_source"),
            nullable=True,
        ),
        sa.Column("initiated_by", sa.Enum("ui", "api", "mcp", name="initiated_by"), nullable=False),
        sa.Column("initiated_by_client", sa.String(length=128), nullable=True),
        sa.Column("raw_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("log_excerpt", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(is_synthetic AND synthetic_source IS NOT NULL)"
            " OR (NOT is_synthetic AND synthetic_source IS NULL)",
            name=op.f("ck_run_synthetic_source_matches_flag"),
        ),
        sa.CheckConstraint("gpu_count >= 1", name=op.f("ck_run_gpu_count_positive")),
        sa.CheckConstraint("pipeline_parallel_size >= 1", name=op.f("ck_run_pp_positive")),
        sa.CheckConstraint("tensor_parallel_size >= 1", name=op.f("ck_run_tp_positive")),
        sa.ForeignKeyConstraint(["gpu_host_id"], ["gpu_host.id"], name=op.f("fk_run_gpu_host_id")),
        sa.ForeignKeyConstraint(
            ["server_config_id"], ["server_config.id"], name=op.f("fk_run_server_config_id")
        ),
        sa.ForeignKeyConstraint(["sweep_id"], ["sweep.id"], name=op.f("fk_run_sweep_id")),
        sa.ForeignKeyConstraint(["workload_id"], ["workload.id"], name=op.f("fk_run_workload_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_index(op.f("ix_run_config_hash"), "run", ["config_hash"], unique=False)
    op.create_index(op.f("ix_run_gpu_host_id"), "run", ["gpu_host_id"], unique=False)
    op.create_index(op.f("ix_run_gpu_model"), "run", ["gpu_model"], unique=False)
    op.create_index(op.f("ix_run_is_synthetic"), "run", ["is_synthetic"], unique=False)
    op.create_index(op.f("ix_run_queued_at"), "run", ["queued_at"], unique=False)
    op.create_index(op.f("ix_run_server_config_id"), "run", ["server_config_id"], unique=False)
    op.create_index(op.f("ix_run_status"), "run", ["status"], unique=False)
    op.create_index(op.f("ix_run_sweep_id"), "run", ["sweep_id"], unique=False)
    op.create_index(
        "ix_run_sweep_id_replicate_idx", "run", ["sweep_id", "replicate_idx"], unique=False
    )
    op.create_index(
        op.f("ix_run_tensor_parallel_size"), "run", ["tensor_parallel_size"], unique=False
    )
    op.create_index(op.f("ix_run_vllm_version"), "run", ["vllm_version"], unique=False)
    op.create_index(op.f("ix_run_workload_hash"), "run", ["workload_hash"], unique=False)
    op.create_index(op.f("ix_run_workload_id"), "run", ["workload_id"], unique=False)
    op.create_table(
        "engine_sample",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kv_cache_usage_pct", sa.Float(), nullable=True),
        sa.Column("prefix_cache_hit_rate", sa.Float(), nullable=True),
        sa.Column("num_requests_running", sa.Integer(), nullable=True),
        sa.Column("num_requests_waiting", sa.Integer(), nullable=True),
        sa.Column("num_preemptions_total", sa.BigInteger(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_engine_sample_run_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engine_sample")),
    )
    op.create_index(
        "ix_engine_sample_run_id_sampled_at",
        "engine_sample",
        ["run_id", "sampled_at"],
        unique=False,
    )
    op.create_table(
        "gpu_sample",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sm_utilization_pct", sa.Float(), nullable=True),
        sa.Column("memory_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("power_watts", sa.Float(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("sm_clock_mhz", sa.Integer(), nullable=True),
        sa.Column("memory_clock_mhz", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_gpu_sample_run_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_sample")),
    )
    op.create_index(
        "ix_gpu_sample_run_id_gpu_index_sampled_at",
        "gpu_sample",
        ["run_id", "gpu_index", "sampled_at"],
        unique=False,
    )
    op.create_table(
        "run_summary",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("successful_requests", sa.Integer(), nullable=True),
        sa.Column("benchmark_duration_sec", sa.Float(), nullable=True),
        sa.Column("total_input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("total_generated_tokens", sa.BigInteger(), nullable=True),
        sa.Column("request_throughput_req_sec", sa.Float(), nullable=True),
        sa.Column("output_token_throughput_tok_sec", sa.Float(), nullable=True),
        sa.Column("total_token_throughput_tok_sec", sa.Float(), nullable=True),
        sa.Column("output_token_throughput_per_gpu", sa.Float(), nullable=True),
        sa.Column("total_token_throughput_per_gpu", sa.Float(), nullable=True),
        sa.Column("ttft_ms_mean", sa.Float(), nullable=True),
        sa.Column("ttft_ms_median", sa.Float(), nullable=True),
        sa.Column("ttft_ms_p99", sa.Float(), nullable=True),
        sa.Column("tpot_ms_mean", sa.Float(), nullable=True),
        sa.Column("tpot_ms_median", sa.Float(), nullable=True),
        sa.Column("tpot_ms_p99", sa.Float(), nullable=True),
        sa.Column("itl_ms_mean", sa.Float(), nullable=True),
        sa.Column("itl_ms_median", sa.Float(), nullable=True),
        sa.Column("itl_ms_p99", sa.Float(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_run_summary_run_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_summary")),
    )
    # ### end Alembic commands ###

    op.execute(_RUN_IMMUTABILITY)
    op.execute(_APPEND_ONLY)


def downgrade() -> None:
    op.execute(_DROP)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_summary")
    op.drop_index("ix_gpu_sample_run_id_gpu_index_sampled_at", table_name="gpu_sample")
    op.drop_table("gpu_sample")
    op.drop_index("ix_engine_sample_run_id_sampled_at", table_name="engine_sample")
    op.drop_table("engine_sample")
    op.drop_index(op.f("ix_run_workload_id"), table_name="run")
    op.drop_index(op.f("ix_run_workload_hash"), table_name="run")
    op.drop_index(op.f("ix_run_vllm_version"), table_name="run")
    op.drop_index(op.f("ix_run_tensor_parallel_size"), table_name="run")
    op.drop_index("ix_run_sweep_id_replicate_idx", table_name="run")
    op.drop_index(op.f("ix_run_sweep_id"), table_name="run")
    op.drop_index(op.f("ix_run_status"), table_name="run")
    op.drop_index(op.f("ix_run_server_config_id"), table_name="run")
    op.drop_index(op.f("ix_run_queued_at"), table_name="run")
    op.drop_index(op.f("ix_run_is_synthetic"), table_name="run")
    op.drop_index(op.f("ix_run_gpu_model"), table_name="run")
    op.drop_index(op.f("ix_run_gpu_host_id"), table_name="run")
    op.drop_index(op.f("ix_run_config_hash"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_sweep_status"), table_name="sweep")
    op.drop_index(op.f("ix_sweep_is_synthetic"), table_name="sweep")
    op.drop_index(op.f("ix_sweep_gpu_host_id"), table_name="sweep")
    op.drop_index(op.f("ix_sweep_created_at"), table_name="sweep")
    op.drop_table("sweep")
    op.drop_index(op.f("ix_server_config_parent_id"), table_name="server_config")
    op.drop_index(op.f("ix_server_config_model_id"), table_name="server_config")
    op.drop_index(op.f("ix_server_config_created_at"), table_name="server_config")
    op.drop_table("server_config")
    op.drop_index(op.f("ix_gpu_device_gpu_host_id"), table_name="gpu_device")
    op.drop_table("gpu_device")
    op.drop_index(op.f("ix_workload_created_at"), table_name="workload")
    op.drop_table("workload")
    op.drop_index(op.f("ix_model_created_at"), table_name="model")
    op.drop_table("model")
    op.drop_index(op.f("ix_gpu_host_created_at"), table_name="gpu_host")
    op.drop_table("gpu_host")
    # ### end Alembic commands ###
